### ISSUE TITLE
如何自定义页面？

### ISSUE THREAD

**Issue by dishao123** [crazypeace/gh-proxy#3]
大佬，你好我想把前端页面换成[ghps.cc](https://ghps.cc)，应该怎么添加上转换输入框和按钮？

**Comment by crazypeace** [comment]
你好， 没懂你的意思。

你是说，要换用 ghps.cc 来代理？
但是，传统的 ghproxy 只能处理一层github脚本里的资源。
如果要处理无限嵌套调用，要在worker的代码里面改点东西（这里和传统的github proxy不一样）
https://github.com/crazypeace/gh-proxy/blob/0ac4cd28c02eceb1951539fbe549bbc26eb698c4/worker.js#L122
![image](https://github.com/user-attachments/assets/30f25f42-28d1-49d4-ade0-38a306ea7cb0)
